M48
; DRILL file {KiCad (6.0.8-1)-1} date Wednesday, January 11, 2023 at 02:40:22 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-11T14:40:22-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.8-1)-1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
%
G90
G05
T1
X6.0415Y-2.3337
T1
G00X6.0415Y-2.113
M15
G01X6.0415Y-2.0993
M16
G05
T0
M30
